<a href="https://colab.research.google.com/github/ravitata/tensorflow2/blob/master/tf-data-learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print (tf.__version__)

2.3.0


In [4]:
#output is scalar
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5]) # 1D
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int32>


In [10]:
#output is 1D tensor
dataset = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5, 6]]) # 2D 3*2
print(dataset)
print("")
print(list(dataset.as_numpy_iterator()))
print("")
for ele in dataset:
  print(ele)
  print(ele.numpy())

<TensorSliceDataset shapes: (2,), types: tf.int32>

[array([1, 2], dtype=int32), array([3, 4], dtype=int32), array([5, 6], dtype=int32)]

tf.Tensor([1 2], shape=(2,), dtype=int32)
[1 2]
tf.Tensor([3 4], shape=(2,), dtype=int32)
[3 4]
tf.Tensor([5 6], shape=(2,), dtype=int32)
[5 6]


In [18]:
dataset = tf.data.Dataset.from_tensor_slices(tf.random.normal([3, 2])) #1D tensor
print(dataset)
print("")
print(dataset.element_spec)
print("")
print(dataset.cardinality()) #Return number of elements

<TensorSliceDataset shapes: (2,), types: tf.float32>

TensorSpec(shape=(2,), dtype=tf.float32, name=None)

tf.Tensor(3, shape=(), dtype=int64)


In [27]:
dataset = tf.data.Dataset.from_tensor_slices(
    (
        [[1,2], [3,4], [5,6]],
        ['A', 'B','C']
    )
)
print(dataset.element_spec)
print("")

for elem in dataset:
  print(elem)
print("")

for elem in dataset.take(2):
  print(elem)

(TensorSpec(shape=(2,), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.string, name=None))

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'A'>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'B'>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'C'>)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'A'>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'B'>)


In [28]:
from tensorflow.keras.datasets import cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()


170500096/170498071 [==============================] - 11s 0us/step
