<a href="https://colab.research.google.com/github/ravitata/tensorflow2/blob/master/tf-data-learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print (tf.__version__)

2.3.0


In [3]:
#output is scalar
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5]) # 1D
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int32>


In [4]:
#output is 1D tensor
dataset = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5, 6]]) # 2D 3*2
print(dataset)
print("")
print(list(dataset.as_numpy_iterator()))
print("")
for ele in dataset:
  print(ele)
  print(ele.numpy())

<TensorSliceDataset shapes: (2,), types: tf.int32>

[array([1, 2], dtype=int32), array([3, 4], dtype=int32), array([5, 6], dtype=int32)]

tf.Tensor([1 2], shape=(2,), dtype=int32)
[1 2]
tf.Tensor([3 4], shape=(2,), dtype=int32)
[3 4]
tf.Tensor([5 6], shape=(2,), dtype=int32)
[5 6]


In [5]:
dataset = tf.data.Dataset.from_tensor_slices(tf.random.normal([3, 2])) #1D tensor
print(dataset)
print("")
print(dataset.element_spec)
print("")
print(dataset.cardinality()) #Return number of elements

<TensorSliceDataset shapes: (2,), types: tf.float32>

TensorSpec(shape=(2,), dtype=tf.float32, name=None)

tf.Tensor(3, shape=(), dtype=int64)


In [6]:
dataset = tf.data.Dataset.from_tensor_slices(
    (
        [[1,2], [3,4], [5,6]],
        ['A', 'B','C']
    )
)
print(dataset.element_spec)
print("")

for elem in dataset:
  print(elem)
print("")

for elem in dataset.take(2):
  print(elem)

(TensorSpec(shape=(2,), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.string, name=None))

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'A'>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'B'>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'C'>)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'A'>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'B'>)


In [26]:
from tensorflow.keras.datasets import cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()

num_classes = 10 
y_train = tf.keras.utils.to_categorical(y_train, num_classes = num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes = num_classes )

dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
print(dataset.element_spec)
print('')
print(dataset.cardinality())


(TensorSpec(shape=(32, 32, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(10,), dtype=tf.float32, name=None))

tf.Tensor(50000, shape=(), dtype=int64)


In [27]:
dataset = dataset.batch(64)

In [9]:
import numpy as np
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Conv2D, Dense, Flatten
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [10]:
inputs = Input((32,32,3))
h = Conv2D(8, kernel_size=3,activation='relu')(inputs)
h = Conv2D(18, kernel_size=3, activation='relu')(h)
h = Flatten()(h)
outputs = Dense(10, activation='softmax')(h)
model = Model(inputs=inputs, outputs=outputs)

rmsprop = RMSprop(learning_rate=1e-3)
model.compile(optimizer=rmsprop, loss='categorical_crossentropy', metrics=['accuracy'])

In [11]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 32, 32, 3)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 30, 30, 8)         224       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 28, 28, 18)        1314      
_________________________________________________________________
flatten (Flatten)            (None, 14112)             0         
_________________________________________________________________
dense (Dense)                (None, 10)                141130    
Total params: 142,668
Trainable params: 142,668
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(x_train.shape)
print(y_train.shape)

(50000, 32, 32, 3)
(50000, 10)


In [13]:
# Calculate the training generator and test generator steps per epoch
batch_size=64
train_steps_per_epoch = x_train.shape[0] // batch_size
#val_steps = val_generator.n // val_generator.batch_size
#print(train_steps_per_epoch, val_steps)
print(train_steps_per_epoch)

781


In [28]:
print(dataset.element_spec)

(TensorSpec(shape=(None, 32, 32, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(None, 10), dtype=tf.float32, name=None))


In [15]:
model.fit(dataset, epochs=1, steps_per_epoch = train_steps_per_epoch)

781/781 [==============================] - 3s 3ms/step - loss: 4.5506 - accuracy: 0.2520


In [16]:
img_datagen = ImageDataGenerator(rotation_range=20, width_shift_range=0.2)
img_datagen.fit(x_train)

dataset_1 = tf.data.Dataset.from_generator(img_datagen.flow,
                                         args = [x_train, y_train, batch_size],
                                         output_types = (tf.float32, tf.int32),
                                         output_shapes = ([batch_size, 32,32,3], [batch_size,10])
                                         ) 
                                    

In [17]:
model.fit(dataset_1, epochs=1, steps_per_epoch = train_steps_per_epoch)

781/781 [==============================] - 23s 29ms/step - loss: 1.9874 - accuracy: 0.2989


## Using map and filter functions

In [203]:
from tensorflow.keras.datasets import cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
#dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))

num_classes = 10 
y_train = tf.keras.utils.to_categorical(y_train, num_classes = num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes = num_classes )

dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))

print(dataset.element_spec)
print('')
print(dataset.cardinality())

(TensorSpec(shape=(32, 32, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(10,), dtype=tf.float32, name=None))

tf.Tensor(50000, shape=(), dtype=int64)


In [204]:
def rescale(image, label):
  return image/255, label

def label_filter(image, label):
  x = tf.constant([0,0,0,0,0,0,0,0,0,1], dtype=tf.float32)
  print(tf.math.equal(label, x))
  return False

In [205]:
dataset=dataset.map(rescale)
dataset.filter(label_filter)

#dataset = dataset.shuffle(256)
#dataset = dataset.batch(64,drop_remainder=True )
#dataset = dataset.repeat(5) #epochs

#print(dataset.element_spec)
print('')
print(dataset.cardinality())

Tensor("Equal:0", shape=(10,), dtype=bool)

tf.Tensor(50000, shape=(), dtype=int64)


In [208]:
x = tf.constant([0,0,0,0,0,0,0,0,0,1], dtype=tf.float32)
for ele in dataset:
  print(tf.math.equal(ele[1], x))
  print(ele[1].numpy())

Streaming output truncated to the last 5000 lines.
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
tf.Tensor([ True  True False  True  True  True  True  True  True False], shape=(10,), dtype=bool)
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
tf.Tensor([ True  True  True  True  True  True  True  True  True  True], shape=(10,), dtype=bool)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
tf.Tensor([ True  True  True  True  True  True  True  True False False], shape=(10,), dtype=bool)
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
tf.Tensor([ True  True  True  True  True False  True  True  True False], shape=(10,), dtype=bool)
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
tf.Tensor([ True  True  True  True  True  True  True False  True False], shape=(10,), dtype=bool)
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
tf.Tensor([ True  True False  True  True  True  True  True  True False], shape=(10,), dtype=bool)
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
tf.Tensor([ True  True  True False  True  True  True  True  True False], shape=(10,), dtype=bool)
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
tf.Tens

KeyboardInterrupt: ignored

In [196]:
history = model.fit(dataset)

781/781 [==============================] - 5s 6ms/step - loss: 1.4154 - accuracy: 0.5111


In [37]:
781*5

3905

In [114]:
#output is 1D tensor
dataset = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5, 6]]) # 2D 3*2
print(dataset)
print("")
print(list(dataset.as_numpy_iterator()))
print("")
for ele in dataset:
  print(ele)
  print(ele.numpy())

<TensorSliceDataset shapes: (2,), types: tf.int32>

[array([1, 2], dtype=int32), array([3, 4], dtype=int32), array([5, 6], dtype=int32)]

tf.Tensor([1 2], shape=(2,), dtype=int32)
[1 2]
tf.Tensor([3 4], shape=(2,), dtype=int32)
[3 4]
tf.Tensor([5 6], shape=(2,), dtype=int32)
[5 6]


In [214]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 1], [2, 2], [3,3]])
dataset = dataset.filter(lambda x: x[0] < 3)
print(list(dataset.as_numpy_iterator()))

# `tf.math.equal(x, y)` is required for equality comparison
def filter_fn(x):
  return tf.math.less(x[0], 3)
dataset = dataset.filter(filter_fn)
print(list(dataset.as_numpy_iterator()))


[array([1, 1], dtype=int32), array([2, 2], dtype=int32)]
[array([1, 1], dtype=int32), array([2, 2], dtype=int32)]
